apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: signalserver
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: signalserver
        tier: backend
        track: stable
    spec:
      containers:
        - name: signalserver
          image: sigmundgranaas/signalserver
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
